#!/usr/bin/env python3

# Copyright 2013, 2014, 2015, 2016, 2017, 2020, 2022 Andrzej Cichocki

# This file is part of pyven.
#
# pyven is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# pyven is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pyven.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import division
from argparse import ArgumentParser
from inspect import getsource
from pathlib import Path
from shlex import quote
from shutil import copyfileobj
from subprocess import check_call
from tempfile import TemporaryDirectory
from urllib.request import urlopen
import os, re, sys

initbinname = 'initbin.py'

def activate():
    parser = ArgumentParser()
    parser.add_argument('projectdir', type = lambda s: Path(s).resolve())
    projectdir = parser.parse_args().projectdir
    bindir = projectdir / 'bin'
    bindir.mkdir(exist_ok = True)
    venvpool = bindir / 'venvpool.py'
    with urlopen('https://raw.githubusercontent.com/combatopera/pyven/v86/venvpool.py') as f, venvpool.open('wb') as g:
        copyfileobj(f, g)
    with TemporaryDirectory() as bootdir:
        bootdir = Path(bootdir)
        (bootdir / 'requirements.txt').write_text('pyven>=86')
        initbinpath = bootdir / initbinname
        initbinpath.write_text(getsource(sys.modules[__name__]))
        bindirstr = str(bindir)
        check_call([sys.executable, str(venvpool), '--', str(initbinpath), str(projectdir), bindirstr, str(venvpool)])
    try:
        dirstrs = os.environ['PATH'].split(os.pathsep)
    except KeyError:
        dirstrs = []
    if bindirstr in dirstrs:
        print('# Already activated.')
    else:
        dirstrs.append(bindirstr)
        print('# Please eval this line in your shell:')
        print('PATH=' + quote(os.pathsep.join(dirstrs)))

def initbin():
    from pyven.initscripts import executablebits
    from pyven.mainmodules import checkpath, commandornone, scriptregex
    scriptpattern = re.compile(scriptregex, re.MULTILINE)
    parser = ArgumentParser()
    parser.add_argument('root', type = Path)
    parser.add_argument('bindir', type = Path)
    parser.add_argument('venvpoolpath')
    args = parser.parse_args()
    root = args.root
    bindir = args.bindir
    venvpoolpathstr = args.venvpoolpath
    for srcpath in root.glob('**/*.py'):
        if checkpath(str(root), srcpath) and scriptpattern.search(srcpath.read_text()) is not None:
            command = commandornone(srcpath)
            if command is None:
                continue
            scriptpath = bindir / command
            srcpathstr = str(srcpath)
            with scriptpath.open('w') as f:
                f.write("""#!/usr/bin/env python3
import sys
sys.argv[1:1] = '--', {srcpathstr!r}
__file__ = {venvpoolpathstr!r}
with open(__file__) as f: text = f.read()
del sys, f
exec('del text\\n' + text)
""".format(**locals()))
            os.chmod(scriptpath, os.stat(scriptpath).st_mode | executablebits)

if ('__main__' == __name__):
    (initbin if initbinname == Path(sys.argv[0]).name else activate)()
