#!/bin/bash

set -ex

tempdir=$(mktemp -d)

trap 'rm -r $tempdir' EXIT

function initbootvenv {

    bootvenv=$tempdir/$version

    virtualenv -p python$version $bootvenv

    $bootvenv/bin/pip install "$@" pyven

}

function initoptvenv {

    $bootvenv/bin/initopt "$@" ~/opt/venv$version

}

version=3

initbootvenv

initoptvenv "$@"

version=2

initbootvenv setuptools==44.1.1 twine==1.15.0

initoptvenv --solver legacy
