#!/bin/bash

set -eux

tempdir=$(mktemp -d)

trap 'rm -r $tempdir' EXIT

function initbootvenv {

    bootvenv=$tempdir/$version

    virtualenv -p python$version $bootvenv

    $bootvenv/bin/pip install "$@" pyven

    (

        cd "$(dirname "$0")"

        # TODO: Inspect project.arid to get these names.
        for p in ../aridity ../diapyr ../lagoon .; do

            (cd $p; $bootvenv/bin/pipify)

            $bootvenv/bin/pip install -e $p

        done

    )

}

version=3

initbootvenv

$bootvenv/bin/initopt "$@" "$USER_OPT"
