#!/bin/bash

cd "$(dirname "$0")"

for tag in XXX TODO FIXME; do

  find '(' -name '*.py' -or -name '*.pyx' ')' -exec pcregrep --color=always "$tag LATER" '{}' +

  find '(' -name '*.py' -or -name '*.pyx' ')' -exec pcregrep --color=always "$tag(?! LATER)" '{}' +

done
