#!/bin/bash

set -e

while ! [[ -e .hg || -e .svn ]]; do cd ..; done

(

    export PYTHONPATH="$PWD"
    IFS=$'\n'

    licheck.py $(
        find '(' -name '*.py' -or -name '*.pyx' -or -name '*.s' -or -name '*.sh' ')' -exec hg st -A '{}' + |
        grep -v '^[IR ]' |
        cut -c 3-
    )
    echo licheck: OK >&2

    divcheck.py $(find -name '*.py')
    echo divcheck: OK >&2

    execcheck.py $(find -name '*.py')
    echo execcheck: OK >&2

)

eval "notexpr=($(cat .flakesignore))"

{ find -name '*.py' -not '(' "${notexpr[@]}" ')' -exec "$MINICONDA_HOME/bin/pyflakes" '{}' + && echo pyflakes: OK; } >&2

runpy -c 'import nose; nose.main()' --exe -v
