#!/bin/bash

set -e

cd "$(dirname "$0")"

(
    export PYTHONPATH="$PWD"
    IFS=$'\n'
    "$(dirname "$(readlink -f "$0")")"/licheck.py $(
        find '(' -name '*.py' -or -name '*.pyx' -or -name '*.s' -or -name '*.sh' ')' -exec hg st -A '{}' + |
        grep -v ^I |
        cut -c 3-
    )
    echo licheck: OK >&2
)

eval "notexpr=($(cat .flakesignore))"

{ find -name '*.py' -not '(' "${notexpr[@]}" ')' -exec pyflakes '{}' + && echo pyflakes: OK; } >&2

nosetests --exe -v
